# Generated by Django 4.2.24 on 2025-09-16 21:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('uiid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='clients.client')),
                ('productos', models.ManyToManyField(related_name='compras', to='products.product')),
            ],
        ),
    ]
