# Generated by Django 4.2.24 on 2025-09-17 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='uiid',
            new_name='uuid',
        ),
    ]
