CREATE TABLE "Usuarios" (
  "id_usuario" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- UUID
  "nombre_usuario" varchar,
  "email" varchar,
  "password" varchar, -- hashed password
  "rol_id" int
);

CREATE TABLE "Roles" (
  "id_rol" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- UUID
  "nombre_rol" varchar -- e.g., 'admin', 'user'
);

CREATE TABLE "Clientes" (
  "id_cliente" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- UUID
  "tipo_documento" varchar,
  "documento" varchar,
  "nombre" varchar,
  "apellido" varchar,
  "direccion" varchar,
  "telefono" varchar,
  "fecha_nacimiento" date,
  "url_imagen" varchar
);

CREATE TABLE "Proveedores" (
  "id_proveedor" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- UUID
  "nit" varchar,
  "nombre" varchar,
  "ciudad" varchar,
  "correo" varchar,
  "telefono" varchar
);

CREATE TABLE "Productos" (
  "id_producto" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- UUID
  "nombre" varchar,
  "categoria" varchar,
  "marca" varchar,
  "valor_unitario" decimal,
  "stock" int,
  "descripcion" text,
  "proveedor_id" int
);

CREATE TABLE "Compras" (
  "id_compra" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- UUID 
  "cliente_id" int,
  "fecha_compra" datetime
);

CREATE TABLE "Detalle_Compra" (
  "id_detalle" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "compra_id" int,
  "producto_id" int,
  "cantidad" int,
  "valor_unitario" decimal
);

ALTER TABLE "Usuarios" ADD FOREIGN KEY ("rol_id") REFERENCES "Roles" ("id_rol");

ALTER TABLE "Productos" ADD FOREIGN KEY ("proveedor_id") REFERENCES "Proveedores" ("id_proveedor");

ALTER TABLE "Compras" ADD FOREIGN KEY ("cliente_id") REFERENCES "Clientes" ("id_cliente");

ALTER TABLE "Detalle_Compra" ADD FOREIGN KEY ("compra_id") REFERENCES "Compras" ("id_compra");

ALTER TABLE "Detalle_Compra" ADD FOREIGN KEY ("producto_id") REFERENCES "Productos" ("id_producto");
